spring:
  application:
    name: cliente-service

  datasource:
    url: jdbc:postgresql://localhost:5432/clienteKart
    username: postgres
    password: clave

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${PORT:${SERVER_PORT:0}}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
