spring:
  application:
    name: cliente-service
  datasource:
    url: jdbc:postgresql://localhost:5432/clienteKart
    username: postgres
    password: clave # Considera usar Spring Cloud Config Server para encriptar contrase침as
  jpa:
    hibernate:
      ddl-auto: update # 'validate' o 'none' es m치s seguro para producci칩n
    show-sql: true

server:
  port: ${PORT:${SERVER_PORT:0}} # Puerto din치mico

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl: # Corregido a camelCase
      defaultZone: http://localhost:8080/eureka/ # Actualizado al puerto de Eureka Server
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}} # Corregido a camelCase