spring:
  application:
    name: descuento-especial-service # Nombre de aplicación añadido
  datasource:
    url: jdbc:postgresql://localhost:5432/descuentoEspecialKart
    username: postgres
    password: clave # Considera usar Spring Cloud Config Server para encriptar contraseñas
  jpa:
    hibernate:
      ddl-auto: update # 'validate' o 'none' es más seguro para producción
    show-sql: true

server:
  port: ${PORT:${SERVER_PORT:0}} # Puerto dinámico

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl: # Corregido a camelCase
      defaultZone: http://localhost:8080/eureka/ # Actualizado al puerto de Eureka Server
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}} # Corregido a camelCase