server:
  port: 8080

eureka:
  instance:
    hostname: eureka-server-service
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka-server-service:8080/eureka/

spring:
  application:
    name: eureka-server