server:
  port: 8090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # Cliente Service
        - id: cliente-service
          uri: lb://cliente-service
          predicates:
            - Path=/cliente/**
          filters:
            - StripPrefix=1

        # Reserva Service
        - id: reserva-service
          uri: lb://reserva-service
          predicates:
            - Path=/reserva/**
          filters:
            - StripPrefix=1

        # Descuento Grupo Service
        - id: descuento-persona-service
          uri: lb://descuento-persona-service
          predicates:
            - Path=/grupo/**
          filters:
            - StripPrefix=1

        # Tarifa Service
        - id: tarifa-service
          uri: lb://tarifa-service
          predicates:
            - Path=/tarifa/**
          filters:
            - StripPrefix=1

        # Descuento Frecuente Service
        - id: descuento-frecuente-service
          uri: lb://descuento-frecuente-service
          predicates:
            - Path=/frecuente/**
          filters:
            - StripPrefix=1

        # Descuento Especial Service
        - id: descuento-especial-service
          uri: lb://descuento-especial-service
          predicates:
            - Path=/especial/**
          filters:
            - StripPrefix=1
