spring:
  application:
    name: rack-service
  datasource:
    url: jdbc:postgresql://localhost:5432/rackKart
    username: postgres
    password: clave
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${PORT:${SERVER_PORT:0}} # Puerto dinámico

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
