server:
  port: 0 # Puerto dinámico

spring:
  application:
    name: rack-service
  cloud:
    config:
      uri: http://config-server-service:8081
      fail-fast: true
  datasource:
    url: ${SPRING_DATASOURCE_URL_RACK}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8080/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}